# Generated by Django 5.2.4 on 2025-08-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
