# Generated by Django 5.2.4 on 2025-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
