# Generated by Django 5.2.4 on 2025-08-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
