# Generated by Django 5.2.4 on 2025-08-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('General', 'General'), ('Teacher', 'Teacher')], default='General', max_length=40, null=True),
        ),
    ]
