# Generated by Django 5.2.4 on 2025-07-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='profile',
        ),
    ]
