# Generated by Django 5.2.4 on 2025-08-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_presidentlist_principallist'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentlist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='president_photos/'),
        ),
        migrations.AddField(
            model_name='principallist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='principal_photos/'),
        ),
    ]
