# Generated by Django 5.2 on 2025-08-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_teacher_approved_at_teacher_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
