# Generated by Django 5.2.4 on 2025-07-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managingcommitteemember',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='principalviceprincipal',
            name='institution',
        ),
        migrations.AddField(
            model_name='principalviceprincipal',
            name='message',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
