# Generated by Django 5.2.4 on 2025-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_remove_managingcommitteemember_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalviceprincipal',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
