# Generated by Django 5.2.4 on 2025-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_principalviceprincipal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioninfo',
            name='institution_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution_images/'),
        ),
        migrations.AddField(
            model_name='institutioninfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
    ]
