# Generated by Django 5.2.4 on 2025-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_institutioninfo_institution_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
