# Generated by Django 5.2.4 on 2025-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioninfo',
            name='address_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
