# Generated by Django 5.2.4 on 2025-08-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_institutioninfo_address_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalviceprincipal',
            name='designation',
            field=models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('headmaster', 'Headmaster'), ('headmistress', 'Headmistress')], max_length=20),
        ),
    ]
