# Generated by Django 5.2.4 on 2025-08-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_alter_principalviceprincipal_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioninfo',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutioninfo',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
