# Generated by Django 5.2.4 on 2025-08-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_institutioninfo_mission_institutioninfo_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='date',
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
