# Generated by Django 5.2.4 on 2025-08-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_remove_notice_date_notice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
