# Generated by Django 5.2.4 on 2025-08-26 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0005_galleryitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=20)),
                ('day_of_week', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=150)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='routine_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='syllabus_files/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='result_files/')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='master.classname')),
            ],
        ),
    ]
